### PR TITLE
pseudo arm support

### PR DESCRIPTION
**Pull request by dcarbone**
First pass at limited arm support.  gh action for running tests on arm is as-of-yet untested.

### CODE REVIEW

**Comment by danielchalef** [comment]
Thanks for the PR! The arm64 _Build and Test_ action is failing. Would you mind taking a look? Once done, we can merge the commits.

Additionally, is the `linux` build constraint necessary? Theoretically, `simdjson-go` should work on a recent Intel MacBook running MacOS. I'm unfortunately not able to test this.

**Comment by danielchalef** [comment]
If you can't get your current qemu-based arm64 runner working, I came across the following that might be a useful alternative: https://github.com/uraimo/run-on-arch-action

**Comment by dcarbone** [comment]
> Thanks for the PR! The arm64 _Build and Test_ action is failing. Would you mind taking a look? Once done, we can merge the commits.
> 
> Additionally, is the `linux` build constraint necessary? Theoretically, `simdjson-go` should work on a recent Intel MacBook running MacOS. I'm unfortunately not able to test this.

Mm, good point on macos + x86.  I'll remove the linux constraint.

**Comment by danielchalef** [comment]
Re the action: since the arm64 target is currently for non-production use, I’m comfortable dropping the action for this arch if it is difficult to implement. Hopefully GitHub releases a native arm64 target soon.

**Comment by dcarbone** [comment]
> Re the action: since the arm64 target is currently for non-production use, I’m comfortable dropping the action for this arch if it is difficult to implement. Hopefully GitHub releases a native arm64 target soon.

Oh, for sure.  To be honest this has somewhat selfish roots, as I've wondered about how to test ARM in GHA for a bit now and this gives me a perfect excuse to mess with it :)

**Comment by dcarbone** [comment]
@danielchalef well...its slow, but it works :)

I have some ideas on how to improve performance.

**Comment by dcarbone** [comment]
~alright, caching of go assets has been implemented.  can probably improve further still, but i unfortunately won't have time to do much more on this in the short term.~

~if you're satisfied with its current state, lets merge :)~

I'm updating the readme and updating the build tags, one moment...

**Comment by dcarbone** [comment]
Given the drastic performance reduction when run on ARM, perhaps we should add a flag along the lines of `--yes-really-please-run-slower-on-arm` to prevent attempted "production" runs on cloud-hosted arm envs?

**Comment by danielchalef** [comment]
> Given the drastic performance reduction when run on ARM, perhaps we should add a flag along the lines of `--yes-really-please-run-slower-on-arm` to prevent attempted "production" runs on cloud-hosted arm envs?

Good idea. Perhaps also exit with a non-zero value when run on arm64 without the flag?

**Comment by danielchalef** [comment]
@dcarbone Looks like the tests are now passing. Would you like to merge now or add the `--yes-really-please-run-slower-on-arm` switch to this PR?

**Comment by dcarbone** [comment]
@danielchalef I'll leave that up to you, I added a quick blurb to the README about it. i probably won't have time to implement the flag for a little while, at least :\

**Comment by dcarbone** [comment]
@danielchalef to be clear, I'm OK with merging this now and adding the flag when one of us has time / it becomes a problem :)

**Comment by danielchalef** [comment]
Sounds good. Will get to doing os this pm PT time.

**Pull request merged**
